name: Gerar e Publicar XML do Feed

on:
  push:
    paths:
      - 'Produto da loja yampi.xlsx'
  schedule:
    - cron: '0 10 * * *'

jobs:
  gerar-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório com autenticação
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/".insteadOf https://github.com/
          git clone https://github.com/wilksontec/amelie-feed.git .

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Gerar XML a partir da planilha
        run: python gerar_feed.py

      - name: Commitar e fazer push do XML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add feed_amelie_produtos.xml
          git commit -m "🛠️ Feed atualizado automaticamente" || echo "Sem alterações"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/wilksontec/amelie-feed.git
          git push origin HEAD:main
